version: '3'

services: 
  postgres:
    image: 'bitnami/postgresql'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=psqldocker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=accounts
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

volumes:
  postgresql_data:
    driver: local