version: '3'

services: 
  postgres:
    image: 'bitnami/postgresql'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=psqldocker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=accounts
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - micro-net

  redis:
    image: 'bitnami/redis'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge

volumes:
  postgresql_data:
    driver: local