version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
    env_file:
        - .env
    environment:
      DATABASE_URL: postgresql://psqldocker:docker@postgres:5432/micro_accounts?schema=public
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    # Run in dev Mode: npm run dev:server
    command: npm run dev:server
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres

  postgres:
    image: docker/postgres
    container_name: psqldatabase
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_MULTIPLE_DATABASES=docker:micro_accounts,docker:dbtest
      - POSTGRESQL_PASSWORD=docker
    volumes:
      - ./docker/dbdata:/var/lib/postgresql/data
      - ./docker/postgres/docker-postgresql:/docker-entrypoint-initdb.d
    networks:
      - micro-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9002:80
    networks:
      - micro-net

  redis:
    image: 'bitnami/redis'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
