version: '3'

services:
  # Application
  postgres:
    image: 'bitnami/postgresql'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_MULTIPLE_DATABASES=docker:account_users,docker:dbtest
      - POSTGRESQL_PASSWORD=docker
    volumes:
      - ./docker/dbdata:/var/lib/postgresql/data
      - ./docker/postgres/docker-postgresql:/docker-entrypoint-initdb.d
    networks:
      - app-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9002:80

  redis:
    image: 'bitnami/redis'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=true
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
